const path = require('node:path');
const { FusesPlugin } = require('@electron-forge/plugin-fuses');
const { FuseV1Options, FuseVersion } = require('@electron/fuses');

// The application icons generated by "npm run build-icons". The packager icon is given without an extension on purpose, because it
// picks the .icns or .ico file itself per platform, while the makers below each want one specific file.
const iconBasePath = path.join(__dirname, 'assets', 'icon');

module.exports = {
	packagerConfig: {
		asar: true,
		icon: iconBasePath,
		ignore: [
			// The icons are read from the repository at package time, so they do not need to be copied into the application itself
			/^\/assets($|\/)/,
			/^\/\.vscode($|\/)/,
			/^\/coverage($|\/)/,
			/^\/node_modules\/\.cache($|\/)/,
			/^\/out($|\/)/,
			/^\/tests($|\/)/
		]
	},
	rebuildConfig: {},
	makers: [
		{
			name: '@electron-forge/maker-squirrel',
			config: {
				setupIcon: `${iconBasePath}.ico`
			}
		},
		{
			name: '@electron-forge/maker-zip',
			platforms: [ 'darwin' ]
		},
		{
			name: '@electron-forge/maker-deb',
			config: {
				options: {
					icon: `${iconBasePath}.png`
				}
			}
		},
		{
			name: '@electron-forge/maker-rpm',
			config: {
				options: {
					icon: `${iconBasePath}.png`
				}
			}
		}
	],
	plugins: [
		{
			name: '@electron-forge/plugin-auto-unpack-natives',
			config: {}
		},

		// Fuses are used to enable/disable various Electron functionality
		// at package time, before code signing the application
		new FusesPlugin({
			version: FuseVersion.V1,
			[FuseV1Options.RunAsNode]: false,
			[FuseV1Options.EnableCookieEncryption]: true,
			[FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false,
			[FuseV1Options.EnableNodeCliInspectArguments]: false,
			[FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
			[FuseV1Options.OnlyLoadAppFromAsar]: true
		})
	]
};
