import type { IconProps } from './IconTypes';

/**
 * Generated by ChatGTP
 */
const PriorityUrgentIcon = ({ className, style }: IconProps) => {
	return (
	<svg viewBox='0 0 64 64' fill='none' className={className} style={style}>
		<circle cx='32' cy='32' r='30' fill='currentColor'/>
		<rect x='30' y='14' width='4' height='20' rx='2' fill='#FFFFFF'/>
		<circle cx='32' cy='44' r='3.5' fill='#FFFFFF'/>
	</svg>
	);
};

export default PriorityUrgentIcon;
