import type { IconProps } from 'src/components/icons/IconTypes';

/**
 * Generated by ChatGTP
 * @param props Icon display options.
 * @returns The low-priority icon SVG.
 */
const PriorityLowIcon = (props: IconProps) => {
	const { className, style } = props;

	return (
		<svg viewBox='0 0 64 64' fill='none' className={className} style={style}>
			<circle cx='32' cy='32' r='30' fill='currentColor'/>
			<path d='M32 48 L44 32 H36 V16 H28 V32 H20 Z' fill='#FFFFFF'/>
		</svg>
	);
};

export default PriorityLowIcon;
