import type { ReactElement } from 'react';
import type { IconProps } from 'src/components/icons/IconTypes';

/**
 * Generated by ChatGTP
 * @param props Icon display options.
 * @returns The urgent-priority icon SVG.
 */
const PriorityUrgentIcon = (props: IconProps): ReactElement => {
	const { className, style } = props;

	return (
		<svg viewBox='0 0 64 64' fill='none' className={className} style={style}>
			<circle cx='32' cy='32' r='30' fill='currentColor'/>
			<rect x='30' y='14' width='4' height='20' rx='2' fill='#FFFFFF'/>
			<circle cx='32' cy='44' r='3.5' fill='#FFFFFF'/>
		</svg>
	);
};

export { PriorityUrgentIcon };
