import type { IconProps } from 'src/components/icons/IconTypes';

/**
 * Generated by ChatGTP
 * @param props Icon display options.
 * @returns The normal-priority icon SVG.
 */
const PriorityNormalIcon = (props: IconProps) => {
	const { className, style } = props;

	return (
		<svg viewBox='0 0 64 64' fill='none' className={className} style={style}>
			<circle cx='32' cy='32' r='30' fill='currentColor'/>
			<rect x='16' y='30' width='32' height='4.5' rx='2' fill='#FFFFFF'/>
		</svg>
	);
};

export default PriorityNormalIcon;
