import type { IconProps } from './IconTypes';

/**
 * Generated by ChatGTP
 * @param root0
 * @param root0.className
 * @param root0.style
 */
const PriorityNormalIcon = ({ className, style }: IconProps) => {
	return (
		<svg viewBox='0 0 64 64' fill='none' className={className} style={style}>
			<circle cx='32' cy='32' r='30' fill='currentColor'/>
			<rect x='16' y='30' width='32' height='4.5' rx='2' fill='#FFFFFF'/>
		</svg>
	);
};

export default PriorityNormalIcon;
