import type { IconProps } from './IconTypes';

/**
 * Generated by ChatGTP
 * @param root0
 * @param root0.className
 * @param root0.style
 */
const PriorityHighIcon = ({ className, style }: IconProps) => {
	return (
		<svg viewBox='0 0 64 64' fill='none' className={className} style={style}>
			<circle cx='32' cy='32' r='30' fill='currentColor'/>
			<path d='M32 16 L44 32 H36 V48 H28 V32 H20 Z' fill='#FFFFFF'/>
		</svg>
	);
};

export default PriorityHighIcon;
