import type { IconProps } from './IconTypes';

/**
 * Generated by ChatGTP
 * @param props Icon display options.
 * @returns The high-priority icon SVG.
 */
const PriorityHighIcon = (props: IconProps) => {
	const { className, style } = props;

	return (
		<svg viewBox='0 0 64 64' fill='none' className={className} style={style}>
			<circle cx='32' cy='32' r='30' fill='currentColor'/>
			<path d='M32 16 L44 32 H36 V48 H28 V32 H20 Z' fill='#FFFFFF'/>
		</svg>
	);
};

export default PriorityHighIcon;
